Repository ME-EW/MEEW-Client, pull requests merged in 2022-09, with the labels that each got.

#60 [FIX] scroll extension 수정
  MEEW-Client/MEEW-Client/Info.plist
  MEEW-Client/MEEW-Client/Screens/Select/Controller/SelectVC.swift
Labels: 👩🏻‍💻현주👩🏻‍💻, ✨선택뷰

#63 [FEAT] 서버 연결 완료
  MEEW-Client/MEEW-Client.xcodeproj/project.pbxproj
  MEEW-Client/MEEW-Client/Global/Extensions/UIView+.swift
  MEEW-Client/MEEW-Client/Global/Resources/Colors/CharacterColor.swift
  MEEW-Client/MEEW-Client/Global/Resources/Colors/Palette.swift
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=0.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=0.imageset/bar=0.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=0.imageset/bar=0@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=0.imageset/bar=0@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=1.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=1.imageset/bar=1.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=1.imageset/bar=1@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=1.imageset/bar=1@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=2.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=2.imageset/bar=2.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=2.imageset/bar=2@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=2.imageset/bar=2@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=3.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=3.imageset/bar=3.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=3.imageset/bar=3@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=3.imageset/bar=3@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=4.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=4.imageset/bar=4.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=4.imageset/bar=4@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/bar=4.imageset/bar=4@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/ic_check.imageset/ic_check.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/ic_check.imageset/ic_check@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/ic_check.imageset/ic_check@3x.png
  MEEW-Client/MEEW-Client/Global/Supports/SceneDelegate.swift
  MEEW-Client/MEEW-Client/Networks/APIConstants/APIConstants.swift
  MEEW-Client/MEEW-Client/Networks/APIModels/ChracterRequestModel.swift
  MEEW-Client/MEEW-Client/Networks/APIModels/TodayCharacterRequestModel.swift
  MEEW-Client/MEEW-Client/Networks/APIServices/CharacterService.swift
  MEEW-Client/MEEW-Client/Networks/APIServices/GetTodayCharacter.swift
  MEEW-Client/MEEW-Client/Networks/DataModel.swift
  MEEW-Client/MEEW-Client/Networks/GetToDoService.swift
  MEEW-Client/MEEW-Client/Screens/ToDo/Controller/BottomSheetVC.swift
  MEEW-Client/MEEW-Client/Screens/ToDo/Controller/ContentVC.swift
  MEEW-Client/MEEW-Client/Screens/ToDo/Controller/FinishedModalVC.swift
  MEEW-Client/MEEW-Client/Screens/ToDo/Controller/MyCell.swift
  MEEW-Client/MEEW-Client/Screens/ToDo/Controller/ToDoVC.swift
  MEEW-Client/Podfile.lock
Labels: 👩🏻‍💻주민👩🏻‍💻, 🌱ToDo뷰

#64 [FEAT] 하단 탭바 구현
  MEEW-Client/MEEW-Client.xcodeproj/project.pbxproj
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert.imageset/icn_tab_alert.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert.imageset/icn_tab_alert@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert.imageset/icn_tab_alert@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert_fill.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert_fill.imageset/icn_tab_alert_fill.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert_fill.imageset/icn_tab_alert_fill@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_alert_fill.imageset/icn_tab_alert_fill@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve.imageset/icn_tab_archieve.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve.imageset/icn_tab_archieve@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve.imageset/icn_tab_archieve@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve_fill.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve_fill.imageset/icn_tab_archieve_fill.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve_fill.imageset/icn_tab_archieve_fill@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_archieve_fill.imageset/icn_tab_archieve_fill@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home.imageset/icn_tab_home.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home.imageset/icn_tab_home@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home.imageset/icn_tab_home@3x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home_fill.imageset/Contents.json
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home_fill.imageset/icn_tab_home_fill.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home_fill.imageset/icn_tab_home_fill@2x.png
  MEEW-Client/MEEW-Client/Global/Resources/Images/Assets.xcassets/icn_tab_home_fill.imageset/icn_tab_home_fill@3x.png
  MEEW-Client/MEEW-Client/Global/Supports/SceneDelegate.swift
  MEEW-Client/MEEW-Client/Screens/Tabbar/TabbarViewController.swift
  MEEW-Client/MEEW-Client/Screens/ToDo/Controller/ToDoVC.swift
Labels: 👩🏻‍💻주민👩🏻‍💻
